import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Logo from '@/app/components/Header/Logo/Logo'
import Header from '@/app/components/Header/Header'
import NavBar from '@/app/components/NavBar/NavBar'
import Slider from '@/app/components/Slider/Slider'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header/>
        <NavBar/>
        <Slider/>
      </main>
    </>
  )
}
